import { useMemo, useState } from 'react';
import jsPDF from 'jspdf';
import type { Module } from './types';

type Profile = { name: string; role: string; experience: string; location: string };
const loadList = (key:string) => { try { return JSON.parse(localStorage.getItem(key)||'[]') as string[] } catch { return [] } };
const loadProfile = ():Profile => { try { return JSON.parse(localStorage.getItem('hse-mentor-profile')||'') } catch { return {name:'HSE Learner',role:'Safety Professional',experience:'',location:''} } };

export default function ProgressHub({mode,modules,completedLessons,onBack,onMode}:{mode:'progress'|'profile';modules:Module[];completedLessons:string[];onBack:()=>void;onMode:(m:'progress'|'profile')=>void}) {
  const [profile,setProfile]=useState(loadProfile); const [saved,setSaved]=useState(false);
  const passed=loadList('hse-mentor-passed-modules'), scenarios=loadList('hse-mentor-completed-scenarios');
  const lessons=modules.reduce((n,m)=>n+m.lessons.length,0), lessonPct=Math.round(completedLessons.length/lessons*100);
  const overall=Math.round(lessonPct*.6+(passed.length/modules.length*100)*.3+(scenarios.length/17*100)*.1);
  const badges=useMemo(()=>[
    ['👣','First Step','Complete your first lesson',completedLessons.length>=1],['📚','Committed Learner','Complete 25 lessons',completedLessons.length>=25],['🎯','Assessment Ready','Pass your first module exam',passed.length>=1],['🦺','Practical Thinker','Complete 5 safety scenarios',scenarios.length>=5],['🏅','Foundation Expert','Pass all Foundation modules',modules.filter(m=>m.level==='foundation').every(m=>passed.includes(m.id))],['👑','HSE Mentor Master','Complete all modules and scenarios',passed.length===modules.length&&scenarios.length>=17]
  ] as const,[completedLessons.length,passed.length,scenarios.length,modules]);
  const certificate=(m:Module)=>{const d=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});d.setFillColor(13,48,60);d.rect(0,0,297,210,'F');d.setDrawColor(231,184,41);d.setLineWidth(2);d.rect(10,10,277,190);d.setTextColor(231,184,41);d.setFont('helvetica','bold');d.setFontSize(18);d.text('HSE MENTOR',148.5,35,{align:'center'});d.setTextColor(255,255,255);d.setFontSize(30);d.text('CERTIFICATE OF COMPLETION',148.5,61,{align:'center'});d.setFont('helvetica','normal');d.setFontSize(14);d.text('This certificate is awarded to',148.5,83,{align:'center'});d.setTextColor(68,211,159);d.setFont('helvetica','bold');d.setFontSize(27);d.text(profile.name||'HSE Learner',148.5,104,{align:'center'});d.setTextColor(255,255,255);d.setFont('helvetica','normal');d.setFontSize(13);d.text('for successfully completing',148.5,121,{align:'center'});d.setFont('helvetica','bold');d.setFontSize(19);d.text(m.title,148.5,137,{align:'center',maxWidth:240});d.setFont('helvetica','normal');d.setFontSize(11);d.text(`Module ${m.order} · ${m.level.toUpperCase()} LEVEL · Passing requirement achieved`,148.5,154,{align:'center'});d.line(43,176,110,176);d.line(187,176,254,176);d.text('Learner',76.5,183,{align:'center'});d.text(new Date().toLocaleDateString(),220.5,183,{align:'center'});d.save(`HSE-Mentor-Module-${m.order}-Certificate.pdf`)};
  if(mode==='profile') return <main className="progress-page"><header className="progress-top"><button onClick={onBack}>←</button><div><strong>My Profile</strong><small>Personal learning record</small></div></header><section className="profile-hero"><div>{(profile.name||'H').charAt(0).toUpperCase()}</div><h1>{profile.name||'HSE Learner'}</h1><p>{profile.role}</p><span>Overall progress {overall}%</span></section><section className="profile-form"><h2>Professional details</h2><label>Full name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Current role<select value={profile.role} onChange={e=>setProfile({...profile,role:e.target.value})}><option>Safety Professional</option><option>Safety Officer</option><option>HSE Supervisor</option><option>HSE Engineer</option><option>HSE Manager</option><option>Student / Beginner</option></select></label><label>HSE experience<input value={profile.experience} onChange={e=>setProfile({...profile,experience:e.target.value})} placeholder="Example: 10 years"/></label><label>Country / location<input value={profile.location} onChange={e=>setProfile({...profile,location:e.target.value})} placeholder="Example: Saudi Arabia"/></label><button onClick={()=>{localStorage.setItem('hse-mentor-profile',JSON.stringify(profile));setSaved(true);setTimeout(()=>setSaved(false),2000)}}>{saved?'✓ Profile Saved':'Save Profile'}</button></section><section className="profile-summary"><h2>Learning record</h2><div><b><strong>{completedLessons.length}</strong>Lessons</b><b><strong>{passed.length}</strong>Exams</b><b><strong>{scenarios.length}</strong>Scenarios</b></div></section><HubNav mode={mode} onMode={onMode}/></main>;
  const levels=['foundation','intermediate','advanced','management'] as const;
  return <main className="progress-page"><header className="progress-top"><button onClick={onBack}>←</button><div><strong>My Progress</strong><small>Learning · Practice · Achievement</small></div></header><section className="progress-hero"><div className="overall-ring" style={{'--progress':`${overall*3.6}deg`} as React.CSSProperties}><span><strong>{overall}%</strong><small>Overall</small></span></div><div><small>WELCOME BACK</small><h1>{profile.name||'HSE Learner'}</h1><p>Continue building your professional HSE knowledge.</p></div></section><section className="progress-stats"><article><i>📖</i><strong>{completedLessons.length}/{lessons}</strong><span>Lessons</span></article><article><i>✓</i><strong>{passed.length}/{modules.length}</strong><span>Exams Passed</span></article><article><i>⚠</i><strong>{scenarios.length}/17</strong><span>Scenarios</span></article></section><section className="level-progress"><h2>Progress by level</h2>{levels.map(level=>{const ls=modules.filter(m=>m.level===level).flatMap(m=>m.lessons),done=ls.filter(l=>completedLessons.includes(l.id)).length,pct=Math.round(done/ls.length*100);return <article key={level}><div><span>{level}</span><b>{done}/{ls.length} lessons</b><strong>{pct}%</strong></div><i><b style={{width:`${pct}%`}}/></i></article>})}</section><section className="achievement-section"><div className="hub-title"><h2>Achievements</h2><span>{badges.filter(b=>b[3]).length}/{badges.length} unlocked</span></div><div className="badge-grid">{badges.map(b=><article className={b[3]?'unlocked':'locked'} key={b[1]}><i>{b[3]?b[0]:'🔒'}</i><strong>{b[1]}</strong><span>{b[2]}</span></article>)}</div></section><section className="certificate-section"><div className="hub-title"><h2>Certificates</h2><span>{passed.length} available</span></div>{passed.length===0?<div className="empty-certificate"><i>🎓</i><strong>No certificate unlocked yet</strong><p>Complete 10 lessons and pass a module assessment to unlock its certificate.</p></div>:modules.filter(m=>passed.includes(m.id)).map(m=><article key={m.id}><div><small>MODULE {m.order} · {m.level}</small><strong>{m.title}</strong></div><button onClick={()=>certificate(m)}>Download PDF</button></article>)}</section><HubNav mode={mode} onMode={onMode}/></main>;
}
function HubNav({mode,onMode}:{mode:'progress'|'profile';onMode:(m:'progress'|'profile')=>void}){return <nav className="hub-nav"><button onClick={()=>onMode('progress')} className={mode==='progress'?'active':''}>◎<span>Progress</span></button><button onClick={()=>onMode('profile')} className={mode==='profile'?'active':''}>☻<span>Profile</span></button></nav>}
