import { useState } from 'react';
import { Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from 'docx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

type Row={activity:string;hazard:string;effect:string;l:number;s:number;controls:string;rl:number;rs:number;responsible:string};
type Details={project:string;location:string;task:string;client:string;assessor:string;date:string;workers:string;duration:string};
const activities=['Pre-start planning & mobilization','Material loading / unloading','Material shifting & storage','Work at height','Access equipment setup','Main task execution','Power / hand tools','Housekeeping & demobilization'];
const equipment=['Mobile crane','Forklift / telehandler','MEWP / manlift','Scaffold','Ladder','Chain block / lever hoist','Power tools','Hand tools','Temporary lifeline','Mobile tower','Trolley / pallet truck'];
const people=['Employees','Subcontractors','Visitors','Public / third parties','Other simultaneous work crews'];
const matrix=[['5 Almost certain','5 M','10 H','15 H','20 E','25 E'],['4 Likely','4 L','8 M','12 H','16 H','20 E'],['3 Possible','3 L','6 M','9 M','12 H','15 H'],['2 Unlikely','2 L','4 L','6 M','8 M','10 H'],['1 Rare','1 L','2 L','3 L','4 L','5 M']];
const score=(l:number,s:number)=>l*s;
const band=(n:number)=>n>=17?'Extreme':n>=10?'High':n>=5?'Medium':'Low';
const baseRows:Record<string,Row[]>={
 'Pre-start planning & mobilization':[
  {activity:'Pre-start planning & mobilization',hazard:'Unapproved work, unidentified interfaces or changing conditions',effect:'Uncontrolled exposure, injury, delay or property damage',l:3,s:4,controls:'Approved RAMS and permit; confirm scope, drawings and work area; competent supervisor; pre-start meeting and toolbox talk; verify emergency and rescue arrangements; stop and reassess after any change.',rl:1,rs:4,responsible:'Project Manager / HSE / Supervisor'},
  {activity:'Mobilization to work area',hazard:'Vehicle movement, reversing and interaction with pedestrians',effect:'Struck-by, collision, serious injury or fatality',l:4,s:5,controls:'Approved traffic plan; segregated route; speed limit; inspected vehicle; licensed driver; trained banksman; reversing alarm and beacon; exclusion zone; high-visibility PPE.',rl:1,rs:5,responsible:'Logistics Supervisor / Driver'}],
 'Material loading / unloading':[
  {activity:'Material loading / unloading',hazard:'Falling, shifting or unstable load',effect:'Crushing, trapped fingers, struck-by injury or fatality',l:4,s:5,controls:'Plan unloading sequence; verify load weight and centre of gravity; level ground; certified lifting equipment; competent operator and rigger; taglines; exclusion zone; never stand under or between unsecured loads.',rl:1,rs:5,responsible:'Lifting Supervisor / Rigger'},
  {activity:'Material loading / unloading',hazard:'People entering plant operating radius',effect:'Collision, crushing or amputation',l:4,s:5,controls:'Rigid segregation where practicable; banksman controls movement; agreed signals/radio; remove non-essential persons; parking brake and wheel chocks; engine off before manual release where applicable.',rl:1,rs:5,responsible:'Logistics Supervisor / Banksman'}],
 'Material shifting & storage':[
  {activity:'Material shifting & storage',hazard:'Manual handling of long, sharp or heavy material',effect:'Back strain, hand injury, cuts or crush injury',l:4,s:3,controls:'Avoid manual handling; use trolley, pallet truck, hoist or lifting aid; assess weight and route; team lift; correct grip and posture; gloves; no lifting above shoulder; rotate workers.',rl:1,rs:3,responsible:'Supervisor / Work Crew'},
  {activity:'Material stacking',hazard:'Poor stacking or unsecured materials',effect:'Collapse, rolling material or blocked access',l:3,s:4,controls:'Designated firm storage area; chocks/racks for round or long items; height limits; heavy items below; restrain materials; clear emergency access; routine inspection.',rl:1,rs:4,responsible:'Storekeeper / Supervisor'}],
 'Work at height':[
  {activity:'Work at height',hazard:'Fall from edge, opening or fragile surface',effect:'Major injury, permanent disability or fatality',l:4,s:5,controls:'Avoid height where possible; approved WAH permit and plan; competent medically fit workers; guardrails/platform first; 100% tie-off to certified anchor/lifeline; inspect harness; calculate fall clearance; weather limits; rescue plan and equipment.',rl:1,rs:5,responsible:'WAH Supervisor / HSE Officer'},
  {activity:'Work at height',hazard:'Dropped tools or materials',effect:'Head injury, struck-by injury or fatality below',l:4,s:4,controls:'Barricaded drop zone; tool lanyards; toe boards and debris control; secure loose materials; controlled hand line; hard hats with chin straps; no simultaneous work below.',rl:1,rs:4,responsible:'Supervisor / Work Crew'}],
 'Access equipment setup':[{activity:'Access equipment setup',hazard:'Defective, unstable or incorrectly erected access equipment',effect:'Collapse or fall from height',l:3,s:5,controls:'Select equipment for task and ground; competent erection/operator; pre-use and formal inspection; valid tag/certificate; outriggers and brakes; safe access gate; do not move occupied mobile scaffold.',rl:1,rs:5,responsible:'Competent Person / Supervisor'}],
 'Main task execution':[{activity:'Main task execution',hazard:'Uncontrolled task-specific energy, pinch points or line of fire',effect:'Crushing, cuts, burns or serious injury',l:3,s:4,controls:'Task-specific briefing; isolate hazardous energy; correct work sequence and tools; hands clear of pinch points; exclusion zone; competent supervision; stop-work authority.',rl:1,rs:4,responsible:'Site Supervisor / Work Crew'}],
 'Power / hand tools':[{activity:'Use of power / hand tools',hazard:'Damaged tool, cable, guard or incorrect accessory',effect:'Electric shock, cuts, eye injury or flying fragments',l:3,s:4,controls:'Correct tool selection; pre-use and periodic inspection/colour code; guard and dead-man switch; correct disc RPM; RCD; cable management; authorized repairs only; tag and remove defects; eye/face/hearing protection.',rl:1,rs:4,responsible:'Supervisor / Tool User'}],
 'Housekeeping & demobilization':[{activity:'Housekeeping & demobilization',hazard:'Waste, trailing cables, sharp items or blocked route',effect:'Slip, trip, cut, fire or delayed evacuation',l:3,s:3,controls:'Clean-as-you-go; segregated waste bins; remove sharp objects; route cables safely; keep access and firefighting equipment clear; final joint inspection and permit close-out.',rl:1,rs:3,responsible:'Supervisor / All Workers'}]
};
function equipmentRows(selected:string[]):Row[]{const out:Row[]=[];if(selected.some(x=>['Mobile crane','Forklift / telehandler','Chain block / lever hoist'].includes(x)))out.push({activity:'Mechanical lifting / material handling',hazard:'Dropped or suspended load; equipment overturning',effect:'Fatal struck-by/crushing injury and major damage',l:4,s:5,controls:'Approved lift plan; certified equipment and accessories; competent operator/rigger/signaler; load chart/SWL; ground and outrigger check; pre-use inspection; taglines; exclusion zone; weather monitoring.',rl:1,rs:5,responsible:'Lifting Supervisor'});if(selected.includes('MEWP / manlift'))out.push({activity:'MEWP operation',hazard:'Overturn, entrapment, collision or fall from platform',effect:'Major injury or fatality',l:4,s:5,controls:'Licensed operator; pre-use check and valid certificate; firm level ground; emergency lowering test; anti-entrapment device; harness attached to approved point; exclusion zone; wind limit; rescue arrangement.',rl:1,rs:5,responsible:'MEWP Operator / Supervisor'});if(selected.some(x=>['Scaffold','Mobile tower','Ladder'].includes(x)))out.push({activity:'Access equipment use',hazard:'Fall due to misuse, instability or missing protection',effect:'Serious injury or fatality',l:4,s:5,controls:'Use collective access where practicable; competent inspection and valid tag; firm base; guardrails/toe boards; secure ladder and maintain three points; do not overreach; control access below.',rl:1,rs:5,responsible:'Competent Inspector / Supervisor'});if(selected.includes('Temporary lifeline'))out.push({activity:'Temporary lifeline installation/use',hazard:'Anchor or lifeline failure; pendulum fall',effect:'Fall from height or fatality',l:3,s:5,controls:'Approved engineered system; competent installer; verify certified anchors and span; install/tension to manufacturer instruction; inspect before use; calculate clearance and capacity; rescue plan.',rl:1,rs:5,responsible:'Competent Installer / WAH Supervisor'});return out}

export default function RiskAssessment({onBack}:{onBack:()=>void}){
 const [step,setStep]=useState(1);const [details,setDetails]=useState<Details>({project:'',location:'',task:'',client:'',assessor:'',date:new Date().toISOString().slice(0,10),workers:'',duration:''});const [selectedActivities,setSelectedActivities]=useState<string[]>([]);const [selectedEquipment,setSelectedEquipment]=useState<string[]>([]);const [selectedPeople,setSelectedPeople]=useState<string[]>(['Employees']);const [otherEquipment,setOtherEquipment]=useState('');const [rows,setRows]=useState<Row[]>([]);
 const toggle=(value:string,list:string[],setter:(x:string[])=>void)=>setter(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
 const generate=()=>{const chosen=selectedActivities.length?selectedActivities:['Pre-start planning & mobilization','Main task execution','Housekeeping & demobilization'];setRows([...chosen.flatMap(a=>baseRows[a]||[]),...equipmentRows(selectedEquipment)]);setStep(4);scrollTo({top:0,behavior:'smooth'})};
 const update=(i:number,k:keyof Row,v:string|number)=>setRows(x=>x.map((r,n)=>n===i?{...r,[k]:v}:r));
 const fileBase=()=>`${(details.task||'Risk_Assessment').replace(/[^a-z0-9]+/gi,'_')}_${details.date}`;
 const meta=()=>[['Project',details.project],['Client',details.client],['Location',details.location],['Activity',details.task],['Assessor',details.assessor],['Date',details.date],['No. of workers',details.workers],['Duration',details.duration],['Equipment',[...selectedEquipment,otherEquipment].filter(Boolean).join(', ')],['Persons exposed',selectedPeople.join(', ')]];
 const exportExcel=()=>{const wb=XLSX.utils.book_new();const data=[...meta(),[],['S.No','Activity','Hazard','Hazard Effect','Initial L','Initial S','Initial RF','Control Measure','Residual L','Residual S','Residual RF','Responsible Party'],...rows.map((r,i)=>[i+1,r.activity,r.hazard,r.effect,r.l,r.s,score(r.l,r.s),r.controls,r.rl,r.rs,score(r.rl,r.rs),r.responsible])];const ws=XLSX.utils.aoa_to_sheet(data);ws['!cols']=[{wch:7},{wch:25},{wch:35},{wch:35},{wch:9},{wch:9},{wch:10},{wch:65},{wch:10},{wch:10},{wch:11},{wch:26}];XLSX.utils.book_append_sheet(wb,ws,'Risk Assessment');const mx=XLSX.utils.aoa_to_sheet([['5×5 RISK MATRIX','SEVERITY →','1 Insignificant','2 Minor','3 Moderate','4 Major','5 Catastrophic'],...matrix,['Risk bands','Low 1–4','Medium 5–9','High 10–16','Extreme 17–25']]);XLSX.utils.book_append_sheet(wb,mx,'Fixed Risk Matrix');XLSX.writeFile(wb,`${fileBase()}.xlsx`)};
 const exportPdf=()=>{const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});doc.setFontSize(16);doc.text('RISK ASSESSMENT',14,12);doc.setFontSize(8);let y=18;meta().forEach(([a,b],i)=>doc.text(`${a}: ${b||'-'}`,14+(i%2)*135,y+Math.floor(i/2)*5));y+=28;autoTable(doc,{startY:y,head:[['No.','Activity','Hazard','Hazard Effect','L','S','RF','Control Measure','L','S','RF','Responsible']],body:rows.map((r,i)=>[i+1,r.activity,r.hazard,r.effect,r.l,r.s,`${score(r.l,r.s)} ${band(score(r.l,r.s))}`,r.controls,r.rl,r.rs,`${score(r.rl,r.rs)} ${band(score(r.rl,r.rs))}`,r.responsible]),styles:{fontSize:5.8,cellPadding:1.2,valign:'top'},headStyles:{fillColor:[18,62,48]},columnStyles:{0:{cellWidth:7},1:{cellWidth:24},2:{cellWidth:28},3:{cellWidth:28},4:{cellWidth:7},5:{cellWidth:7},6:{cellWidth:15},7:{cellWidth:67},8:{cellWidth:7},9:{cellWidth:7},10:{cellWidth:15},11:{cellWidth:25}}});doc.addPage('a4','landscape');doc.setFontSize(15);doc.text('FIXED 5×5 RISK MATRIX',14,15);autoTable(doc,{startY:22,head:[['Likelihood / Severity','1 Insignificant','2 Minor','3 Moderate','4 Major','5 Catastrophic']],body:matrix,styles:{fontSize:11,halign:'center',cellPadding:5},headStyles:{fillColor:[18,62,48]}});doc.text('Low 1–4 | Medium 5–9 | High 10–16 | Extreme 17–25',14,100);doc.save(`${fileBase()}.pdf`)};
 const exportWord=async()=>{const cells=(vals:(string|number)[])=>new TableRow({children:vals.map(v=>new TableCell({children:[new Paragraph({children:[new TextRun({text:String(v),size:15})]})]}))});const doc=new Document({sections:[{children:[new Paragraph({text:'RISK ASSESSMENT',heading:HeadingLevel.TITLE}),...meta().map(([a,b])=>new Paragraph({children:[new TextRun({text:`${a}: `,bold:true}),new TextRun(b||'-')]})),new Paragraph(''),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[cells(['No.','Activity','Hazard','Hazard Effect','L','S','RF','Control Measure','L','S','RF','Responsible']),...rows.map((r,i)=>cells([i+1,r.activity,r.hazard,r.effect,r.l,r.s,score(r.l,r.s),r.controls,r.rl,r.rs,score(r.rl,r.rs),r.responsible]))]}),new Paragraph({text:'FIXED 5×5 RISK MATRIX',heading:HeadingLevel.HEADING_1,pageBreakBefore:true}),new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[cells(['Likelihood / Severity','1 Insignificant','2 Minor','3 Moderate','4 Major','5 Catastrophic']),...matrix.map(cells)]}),new Paragraph('Low 1–4 | Medium 5–9 | High 10–16 | Extreme 17–25')]}]});const blob=await Packer.toBlob(doc);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${fileBase()}.docx`;a.click();URL.revokeObjectURL(url)};
 const save=()=>{localStorage.setItem('hse-mentor-professional-ra',JSON.stringify({details,selectedActivities,selectedEquipment,selectedPeople,otherEquipment,rows}));alert('Draft saved on this device.')};
 const add=()=>setRows([...rows,{activity:'',hazard:'',effect:'',l:3,s:3,controls:'',rl:1,rs:3,responsible:'Site Supervisor'}]);
 return <main className="ra-page"><header className="topbar ra-topbar"><button className="back" onClick={onBack}>←</button><div><strong>Professional Risk Assessment</strong><small>Guided 5×5 builder</small></div><span>HSE</span></header><section className="ra-hero"><span>COMPLETE RISK ASSESSMENT BUILDER</span><h1>Nothing important<br/>left behind.</h1><p>Answer each step so the assessment includes the real activities, equipment, people and site interfaces.</p></section><div className="ra-stepbar">{['Job details','Activities','Equipment & people','Review & export'].map((x,i)=><div className={step===i+1?'active':step>i+1?'done':''} key={x}><b>{step>i+1?'✓':i+1}</b><span>{x}</span></div>)}</div>
 {step===1&&<section className="ra-form"><h2>1. Job and project details</h2><p className="step-help">These details will appear at the top of every exported assessment.</p><div className="form-grid">{([['project','Project name'],['client','Client / company'],['location','Exact work location'],['task','Main task / scope'],['assessor','Assessed by'],['date','Assessment date'],['workers','Number of workers'],['duration','Expected duration']] as [keyof Details,string][]).map(([k,label])=><label key={k}>{label}<input type={k==='date'?'date':'text'} value={details[k]} onChange={e=>setDetails({...details,[k]:e.target.value})}/></label>)}</div><button className="primary wizard-next" disabled={!details.task||!details.location} onClick={()=>setStep(2)}>Next: Select Activities →</button></section>}
 {step===2&&<section className="ra-form"><h2>2. What activities are included?</h2><p className="step-help">Select every step from arrival and unloading to final housekeeping.</p><div className="choice-grid">{activities.map(x=><button className={selectedActivities.includes(x)?'choice selected':'choice'} onClick={()=>toggle(x,selectedActivities,setSelectedActivities)} key={x}><i>{selectedActivities.includes(x)?'✓':'+'}</i>{x}</button>)}</div><div className="wizard-buttons"><button className="secondary" onClick={()=>setStep(1)}>← Back</button><button className="primary" disabled={!selectedActivities.length} onClick={()=>setStep(3)}>Next: Equipment & People →</button></div></section>}
 {step===3&&<section className="ra-form"><h2>3. Equipment and exposed people</h2><h3>Which equipment will be used?</h3><div className="choice-grid compact">{equipment.map(x=><button className={selectedEquipment.includes(x)?'choice selected':'choice'} onClick={()=>toggle(x,selectedEquipment,setSelectedEquipment)} key={x}><i>{selectedEquipment.includes(x)?'✓':'+'}</i>{x}</button>)}</div><label>Other equipment<input value={otherEquipment} onChange={e=>setOtherEquipment(e.target.value)} placeholder="Add any equipment not listed"/></label><h3>Who may be exposed?</h3><div className="choice-grid compact">{people.map(x=><button className={selectedPeople.includes(x)?'choice selected':'choice'} onClick={()=>toggle(x,selectedPeople,setSelectedPeople)} key={x}><i>{selectedPeople.includes(x)?'✓':'+'}</i>{x}</button>)}</div><div className="wizard-buttons"><button className="secondary" onClick={()=>setStep(2)}>← Back</button><button className="primary" onClick={generate}>Build Complete Assessment →</button></div></section>}
 {step===4&&<section className="ra-result"><header><div><small>RISK ASSESSMENT FOR</small><h2>{details.task}</h2><p>{details.project} · {details.location} · {details.date}</p></div><div className="ra-actions"><button onClick={save}>Save</button><button onClick={exportPdf}>PDF</button><button onClick={exportWord}>Word</button><button onClick={exportExcel}>Excel</button></div></header><div className="ra-table-wrap"><table><thead><tr><th>S.No</th><th>Activity</th><th>Hazard</th><th>Hazard Effect</th><th colSpan={3}>Initial Risk</th><th>Control Measure</th><th colSpan={3}>Residual Risk</th><th>Responsible Party</th></tr><tr><th/><th/><th/><th/><th>L</th><th>S</th><th>RF</th><th/><th>L</th><th>S</th><th>RF</th><th/></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{i+1}</td>{(['activity','hazard','effect'] as const).map(k=><td key={k}><textarea value={r[k]} onChange={e=>update(i,k,e.target.value)}/></td>)}<td><select value={r.l} onChange={e=>update(i,'l',+e.target.value)}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></td><td><select value={r.s} onChange={e=>update(i,'s',+e.target.value)}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></td><td><b className={`rf ${band(score(r.l,r.s)).toLowerCase()}`}>{score(r.l,r.s)}</b></td><td><textarea value={r.controls} onChange={e=>update(i,'controls',e.target.value)}/></td><td><select value={r.rl} onChange={e=>update(i,'rl',+e.target.value)}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></td><td><select value={r.rs} onChange={e=>update(i,'rs',+e.target.value)}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></td><td><b className={`rf ${band(score(r.rl,r.rs)).toLowerCase()}`}>{score(r.rl,r.rs)}</b></td><td><textarea value={r.responsible} onChange={e=>update(i,'responsible',e.target.value)}/></td></tr>)}</tbody></table></div><button className="add-risk" onClick={add}>+ Add Hazard Row</button><section className="fixed-matrix"><h2>Fixed 5×5 Risk Matrix</h2><p>This matrix remains attached to the assessment and all exports.</p><table><thead><tr><th>Likelihood / Severity</th><th>1 Insignificant</th><th>2 Minor</th><th>3 Moderate</th><th>4 Major</th><th>5 Catastrophic</th></tr></thead><tbody>{matrix.map((r,i)=><tr key={i}>{r.map((c,n)=><td className={n?band(Number(c.split(' ')[0])).toLowerCase():''} key={c}>{c}</td>)}</tr>)}</tbody></table><div className="matrix-legend"><b className="low">Low 1–4</b><b className="medium">Medium 5–9</b><b className="high">High 10–16</b><b className="extreme">Extreme 17–25</b></div></section><p className="ra-disclaimer">This is a professional starting document. A competent person must verify site conditions, legal/client requirements, method statement, emergency arrangements and control implementation before approval.</p><button className="secondary" onClick={()=>setStep(3)}>← Edit Inputs</button></section>}
 </main>
}
